name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: testAdd
      id: testadd
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testAdd
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "RailwayLineTest.testAdd"
        timeout: 10
        max-score: 4
    - name: testSet
      id: testset
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testSet
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "RailwayLineTest.testSet"
        timeout: 10
        max-score: 4
    - name: testRemove
      id: testremove
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testRemove
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "RailwayLineTest.testRemove"
        timeout: 10
        max-score: 4
    - name: testMain
      id: testmain
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testMain
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "ProgD1Test.testMain"
        timeout: 10
        max-score: 4
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTADD_RESULTS: "${{steps.testadd.outputs.result}}"
        TESTSET_RESULTS: "${{steps.testset.outputs.result}}"
        TESTREMOVE_RESULTS: "${{steps.testremove.outputs.result}}"
        TESTMAIN_RESULTS: "${{steps.testmain.outputs.result}}"
      with:
        runners: testadd,testset,testremove,testmain
